use shop;
INSERT INTO category
VALUES
(1, 'Artkuły biurowe'),
(2, 'Artykuły piśmiennicze'),
(3, 'Artykuły papierowe'),
(4, 'Koperty');

use shop;
INSERT INTO products
VALUES
(1, 1, 'Akta osobowe - skoroszyt', 'AO1', 'Skoroszyt z napisem akta osobowe, dopasowany do potrzeb odbiorcy', 1.40),
(2, 1, 'Akta osobowe - teczka', 'AO2', 'Teczka do akt osobowych', 0.90),
(3, 1, 'Blok biurowy A4/100 kart.', 'BB1', 'Blok biurowy A4 liczący 100 kartek ', 2.60),
(4, 1, 'Blok biurowy A5/100 kart.', 'BB2', 'Blok biurowy A4 liczący 100 kartek', 2.10),
(5, 1, 'Blok do flipchartu gładki/20 arkuszy', 'BF1', 'Blok do flipchartu gładki liczący 20 arkuszy', 9.00),
(6, 1, 'Clipy (klipsy archiw.) - 19mm', 'CK1', 'Clipy biurowe o wymiarach 19mm', 0.20),
(7, 1, 'Clipy (klipsy archiw.) - 25mm', 'CK1', 'Clipy biurowe o wymiarach 25mm', 0.25),
(8, 1, 'Clipy (klipsy archiw.) - 32mm', 'CK1', 'Clipy biurowe o wymiarach 32mm', 0.30),
(9, 1, 'Clipy (klipsy archiw.) - 41mm', 'CK1', 'Clipy biurowe o wymiarach 41mm', 0.35),
(10, 1, 'Clipy (klipsy archiw.) - 51mm', 'CK1', 'Clipy biurowe o wymiarach 51mm', 0.40),
(11, 1, 'Clipboard A4 z klapką', 'CK2', 'Clipboard A4 z klapką', 6.40),
(12, 1, 'Clipboard A4 bez klapki', 'CK3', 'Clipboard A4 bez klapki', 7.40),
(13, 1, 'Datownik', 'DK1', 'Długopis automatyczny w kolorze czarnym', 4.40),
(14, 1, 'Dziennik korespondencyjny A4 - 96 kart.', 'DK2', 'Dziennik korespondencyjny A4 składający się z 96 kartek', 8.40),
(15, 1, 'Dziennik korespondencyjny A4 - 200 kart.', 'DK2', 'Dziennik korespondencyjny A4 składający się z 200 kartek', 10.20),
(16, 1, 'Dziurkacz', 'DK3', 'Dziurkacz tradycyjny w kolorze czarnym', 9.40),
(17, 1, 'Etykiety do segregatora wsuwana - 33x152 / 25szt.', 'DK4', 'Etykiety do segregatora wsuwana o wymiarach 33x152 w lości 25 sztuk', 1.20),
(18, 1, 'Etykiety do segregatora wsuwana - 48x152 / 25szt.', 'DK4', 'Etykiety do segregatora wsuwana o wymiarach 48x152 w lości 25 sztuk', 1.20),
(19, 1, 'Gumka do mazania', 'GG1', 'Gumka do mazania w kolorze białym, tradycyjna', 2.20),
(20, 1, 'Gumki recepturki ', 'GG2', 'Paczka gumek recepturek licząca 50 sztuk', 9.30),
(21, 1, 'Identyfikator', 'DK5', 'Identyfikator tradycyjny w kształcie prostokąta', 1.10),
(22, 1, 'Identyfikator z taśmą', 'DK6', 'Identyfikator tradycyjny w kształcie prostokąta z taśmą', 2.10),
(23, 1, 'Kalkulator VECTOR', 'DK7', 'Kalkulator VECTOR', 5.50),
(24, 1, 'Kalkulator CITIZEN', 'DK8', 'Kalkulator CITIZEN', 5.50),
(25, 1, 'Kieszeń samoprzylepna na CD', 'DK9', 'Kieszeń samoprzylepna na CD - opakowanie zawiera 5 sztuk', 3.50),
(26, 1, 'Klej MAGIC', 'KK1', 'Klej MAGIC ze specjalną plastikową wkładką do użycia', 5.50),
(27, 1, 'Klej w sztyfcie', 'KK2', 'Klej w sztyfcie 20g w okrągłym sztywcie', 5.90),
(28, 1, 'Klej w sztyfcie mocny', 'KK3', 'Klej w sztyfcie mocny 25g', 5.90),
(29, 1, 'Klej w płynie', 'KK4', 'Klej w płynie w plastikowej tubce', 3.90),
(30, 1, 'Korektor w butelce ', 'KO1', 'Korektor w butelce z pędzelkiem', 3.80),
(31, 1, 'Korektor Pentel ', 'KO2', 'Korektor Pentel w długopisie o pojemności 12 ml', 4.40),
(32, 1, 'Korektor w myszce ', 'KO3', 'Korektor w myszce - TIPP-EX duży', 2.40),
(33, 1, 'Korektor TOMA', 'KO4', 'Korektor TOMA', 2.20),
(34, 1, 'Koszulki A4 - groszkowe ', 'DK10', 'Koszulki A4 groszkowe zawierający 100 sztuk', 6.10),
(35, 1, 'Koszulki A4 - krystaliczne', 'DK11', 'Koszulki A4 krystaliczne zawierający 100 sztuk', 5.50),
(36, 1, 'Koszulki A4', 'DK12', 'Koszulki A4 z kolorową krawędzią', 4.40),
(37, 1, 'Linijka plastikowa', 'LL1', 'Linijka plastikowa o wymiarach 40 cm', 2.00),
(38, 1, 'Linijka aluminiowa', 'LL2', 'Linijka aluminiowa o wymiarach 40 cm', 2.90),
(39, 1, 'Magnesy kolorowe', 'MG1', 'Magnesy kolorowe w kolorach niebieskim, czerwonym, żółtym, zielonym i czarnym', 8.00),
(40, 1, 'Nożyczki', 'NN1', 'Nożyczki o wymiarach 21 cm w kolorze niebieskim', 4.90),
(41, 1, 'Nożyk biurowy', 'NN2', 'Nożyk biurowy w kolorze żółtym', 5.90),
(42, 1, 'Nożyk do kopert', 'NN3', 'Nożyk do kopert z czarną obsadką', 8.60),
(43, 2, 'Cienkopis', 'CC1', 'Cienkopis standardowy w owalnym kształcie w kolorze czarnym', 2.40),
(44, 2, 'Cienkopis', 'CC2', 'Cienkopis standardowy w owalnym kształcie w kolorze niebieskim', 2.40),
(45, 2, 'Cienkopis', 'CC3', 'Cienkopis standardowy w owalnym kształcie w kolorze czerwonym', 2.40),
(46, 2, 'Cienkopis', 'CC4', 'Cienkopis standardowy w owalnym kształcie w kolorze zielonym', 2.40),
(47, 2, 'Cienkopis pilot V5', 'CC5', 'Cienkopis z dodatkowy tuszem w owalnym kształcie w kolorze czarnym', 2.00),
(48, 2, 'Cienkopis pilot V5', 'CC5', 'Cienkopis z dodatkowy tuszem w owalnym kształcie w kolorze niebieskim', 2.00),
(49, 2, 'Cienkopis pilot V5', 'CC5', 'Cienkopis z dodatkowy tuszem w owalnym kształcie w kolorze czerwonym', 2.00),
(50, 2, 'Cienkopis pilot V5', 'CC5', 'Cienkopis z dodatkowy tuszem w owalnym kształcie w kolorze zielonym', 2.00),
(51, 2, 'Długopis', 'DD1', 'Długopis standardowy z tradycyjną końcówką w kolorze czarnym', 1.50),
(52, 2, 'Długopis', 'DD2', 'Długopis standardowy z tradycyjną końcówką w kolorze niebieskim', 1.50),
(53, 2, 'Długopis Toma', 'DD3', 'Długopis w owalnym kształcie w kolorze czarnym', 3.40),
(54, 2, 'Długopis Toma', 'DD3', 'Długopis w owalnym kształcie w kolorze niebieskim', 3.40),
(55, 2, 'Długopis automatyczny', 'DD4', 'Długopis automatyczny w kolorze czarnym', 4.40),
(56, 2, 'Długopis automatyczny', 'DD4', 'Długopis automatyczny w kolorze niebieskim', 4.40),
(57, 2, 'Długopis automatyczny', 'DD4', 'Długopis automatyczny w kolorze czerwonym', 4.40),
(58, 2, 'Długopis automatyczny', 'DD4', 'Długopis automatyczny w kolorze zielonym', 4.40),
(59, 2, 'Długopis BIC', 'DD5', 'Długopis BIC dostosowany do kształtu dłoni w kolorze czarnym', 1.20),
(60, 2, 'Długopis BIC', 'DD6', 'Długopis BIC dostosowany do kształtu dłoni w kolorze niebieskim', 1.20),
(61, 2, 'Długopis BIC', 'DD7', 'Długopis BIC dostosowany do kształtu dłoni w kolorze czerwonym', 1.20),
(62, 2, 'Długopis BIC', 'DD8', 'Długopis BIC dostosowany do kształtu dłoni w kolorze zielonym', 1.20),
(63, 2, 'Długopis zwykły', 'DD9', 'Długopis zwykły w kolorze niebieskim', 1.40),
(64, 2, 'Długopis na sprężynce', 'DD10', 'Długopis na sprężynce z podstawką w kolorze niebieskim', 2.40),
(65, 2, 'Długopis PILOT G-1', 'DD11', 'Długopis z zatyczką w kolorze czarnym', 5.50),
(66, 2, 'Długopis PILOT G-1', 'DD12', 'Długopis z zatyczką w kolorze niebieskim', 5.50),
(67, 2, 'Długopis PILOT G-1', 'DD13', 'Długopis z zatyczką w kolorze czerwonym', 5.50),
(68, 2, 'Długopis PILOT G-1', 'DD14', 'Długopis z zatyczką w kolorze zielonym', 5.50),
(69, 2, 'Długopis PILOT G-2', 'DD15', 'Długopis klikający w kolorze czarnym', 5.90),
(70, 2, 'Długopis PILOT G-2', 'DD16', 'Długopis klikający w kolorze niebieskim', 5.90),
(71, 2, 'Długopis PILOT G-2', 'DD17', 'Długopis klikający w kolorze czerwonym', 5.90),
(72, 2, 'Długopis PILOT G-2', 'DD18', 'Długopis klikający w kolorze zielonym', 5.90),
(73, 2, 'Długopis żelowy G-O31', 'DD19', 'Długopis żelowy z zatyczką w kolorze czarnym', 4.40),
(74, 2, 'Długopis żelowy G-O31', 'DD20', 'Długopis żelowy z zatyczką w kolorze niebieskim', 4.40),
(75, 2, 'Długopis żelowy G-O31', 'DD21', 'Długopis żelowy z zatyczką w kolorze czerwonym', 4.40),
(76, 2, 'Długopis żelowy G-O31', 'DD22', 'Długopis żelowy z zatyczką w kolorze zielonym', 4.40),
(77, 2, 'Długopis żelowy G-O32', 'DD23', 'Długopis żelowy klikający w kolorze czarnym', 4.40),
(78, 2, 'Długopis żelowy G-O32', 'DD24', 'Długopis żelowy klikający w kolorze niebieskim', 4.40),
(79, 2, 'Długopis żelowy G-O32', 'DD25', 'Długopis żelowy klikający w kolorze czerwonym', 4.40),
(80, 2, 'Długopis żelowy G-O32', 'DD26', 'Długopis żelowy klikający w kolorze zielonym', 4.40),
(81, 2, 'Flamaster', 'FF1', 'Flamaster z zatyczką w kolorze czarnym', 6.00),
(82, 2, 'Flamaster Stabilo Pen 68', 'FF2', 'Flamaster z końcówką w owalnym kształcie z zatyczką w kolorze czarnym', 5.90),
(83, 2, 'Flamaster Stabilo Pen 68', 'FF3', 'Flamaster z końcówką w owalnym kształcie z zatyczką w kolorze niebieskim', 5.90),
(84, 2, 'Marker do CD', 'MM1', 'Marker do płyt CD w kolorze czarnym', 5.90),
(85, 2, 'Marker do CD dwustronny', 'MM2', 'Dwustronny marker do płyt CD w kolorze czarnym', 5.90),
(86, 2, 'Marker Edding 750', 'MM3', 'Marker do podpisywania płyt CD w kolorze czarnym', 6.40),
(87, 2, 'Marker olejowy', 'MM4', 'Marker olejowy w kolorze czarnym/białym z możliością ścieralności markera', 6.40),
(88, 2, 'Marker olejowy PX20-UNI', 'MM5', 'Marker olejowy w kolorze niebieskim z możliością ścieralności', 5.50),
(89, 2, 'Marker permanentny', 'MM6', 'Marker permanentny ze specjalna okrągłą ścietą końcówką w kolorze czarnym', 7.40),
(90, 2, 'Marker permanentny', 'MM7', 'Marker permanentny ze specjalna okrągłą ścietą końcówką w kolorze niebieskim', 7.40),
(91, 2, 'Marker permanentny', 'MM8', 'Marker permanentny ze specjalna okrągłą ścietą końcówką w kolorze czerwonym', 7.40),
(92, 2, 'Marker permanentny', 'MM9', 'Marker permanentny ze specjalna okrągłą ścietą końcówką w kolorze zielonym', 7.40),
(93, 2, 'Marker sucho ścieralny', 'MM10', 'Marker sucho ścieralny w kolorze czarnym', 7.40),
(94, 2, 'Marker sucho ścieralny', 'MM10', 'Marker sucho ścieralny w kolorze niebieskim', 7.40),
(95, 2, 'Marker sucho ścieralny', 'MM10', 'Marker sucho ścieralny w kolorze czerwonym', 7.40),
(96, 2, 'Marker sucho ścieralny', 'MM10', 'Marker sucho ścieralny w kolorze zielonym', 7.40),
(97, 2, 'Ołówek zwykły', 'OO1', 'Ołówek zwykły H-B o tradycyjnym kształcie', 0.40),
(98, 2, 'Ołówek zwykły z gumką', 'OO2', 'Ołówek zwykły z gumką ścieralną o tradycyjnym kształcie', 1.40),
(99, 2, 'Ołówek Stabilo', 'OO3', 'Ołówek Stabilo H, HB z kałczukowym wkładem', 1.20),
(100, 2, 'Ołówek KOH-I-NOOR', 'OO4', 'Ołówek tradycyjny', 1.90),
(101, 2, 'Ołówek automatyczny', 'OO5', 'Ołówek automatyczny 0,5 - 0,7', 2.40),
(102, 2, 'Wkład do długopisu Panel', 'DD27', 'Wkład do długopisu Panel', 1.00),
(103, 2, 'Wkład do długopisu PILOT G-1, PILOT G-2', 'DD28', 'Wkład do długopisu PILOT w kolorze czarnym', 1.10),
(104, 2, 'Wkład do długopisu PILOT G-1, PILOT G-2', 'DD28', 'Wkład do długopisu PILOT w kolorze niebieskim', 1.10),
(105, 2, 'Wkład do długopisu PILOT G-1, PILOT G-2', 'DD28', 'Wkład do długopisu PILOT w kolorze czerwonym', 1.10),
(106, 2, 'Wkład do długopisu PILOT G-1, PILOT G-2', 'DD28', 'Wkład do długopisu PILOT w kolorze zielonym', 1.10),
(107, 2, 'Wkład do długopisu ZENITH', 'DD29', 'Metalowy, oryginalny wkład do długopisu ZENITH w kolorze czarnym', 1.10),
(108, 2, 'Wkład do długopisu ZENITH', 'DD29', 'Metalowy, oryginalny wkład do długopisu ZENITH w kolorze niebieskim', 1.10),
(109, 2, 'Wkład ołówkowy', 'OO6', 'Wkład ołówkowy w rozmiarach 0,5-0,9', 1.50),
110, 2, 'Zakreślacz', 'ZA1', 'Zakreślacz tracycyjny w kolorze różowym', 9.40),
(111, 2, 'Zakreślacz', 'ZA1', 'Zakreślacz tracycyjny w kolorze fioletowym', 9.40),
(112, 2, 'Zakreślacz', 'ZA1', 'Zakreślacz tracycyjny w kolorze pomarańczowym', 9.40),
(113, 2, 'Zakreślacz', 'ZA1', 'Zakreślacz tracycyjny w kolorze żółtym', 9.40),
(114, 2, 'Zakreślacz', 'ZA1', 'Zakreślacz tracycyjny w kolorze niebieskim', 9.40),
(115, 2, 'Zakreślacz', 'ZA1', 'Zakreślacz tracycyjny w kolorze zielonym', 9.40),
(116, 2, 'Zakreślacz STABILO (opakowanie 4 sztuk)', 'ZA2', 'Opakowanie czterech zakreślaczy w kolorze zielonym + czerwonym + pomarańczowym + żółtym', 17.90),
(117, 2, 'Zakreślacz STABILO (opakowanie 6 sztuk)', 'ZA3', 'Opakowanie sześciu zakreślaczy w kolorze zielonym + czerwonym + pomarańczowym + żółtym +różowym + niebieskim', 20.90),
(118, 3, 'Kostka biurowa - biała klejona', 'KB1', 'Kostka biurowa 8,3x8,3 - kostka biała klejona', 9.90),
(119, 3, 'Kostka biurowa - kolorowa klejona', 'KB1', 'Kostka biurowa 8,3x8,3 - kostka kolorowa klejona', 10.90),
(120, 3, 'Kostka biurowa - biała nieklejona', 'KB2', 'Kostka biurowa 8,3x8,3 - kostka biała nieklejona', 7.40),
(121, 3, 'Kostka biurowa - kolorowa nieklejona', 'KB2', 'Kostka biurowa 8,3x8,3 - kostka kolorowa nieklejona', 8.40),
(122, 3, 'Kostka biała + pojemnik', 'KB3', 'Kostka biała nieklejona z kartkami w pojemniku', 12.00),
(123, 3, 'Karteczki żółte samoprzylepne', 'KZ1', 'Karteczki żółte samoprzylepne o wymiarach: 38x51 mm, 40x50 mm, 51x76 mm', 6.00),
(124, 3, 'Kołonotatnik', 'KB4', 'Kołonotatnik w miękkiej okładce A4, 80 kartkowy ', 3.90),
(125, 3, 'Zeszyt A4', 'ZZ1', 'Zeszyt A4 w kolorowych okładkach 96 kartkowy', 4.50),
(126, 3, 'Zeszyt A5 - 32kart.', 'ZZ1', 'Zeszyt A4 w kolorowych okładkach 32 kartkowy', 2.50),
(127, 3, 'Zeszyt A5 - 60kart.', 'ZZ1', 'Zeszyt A4 w kolorowych okładkach 60 kartkowy', 3.50),
(128, 3, 'Zeszyt A5 - 80kart.', 'ZZ1', 'Zeszyt A4 w kolorowych okładkach 80 kartkowy', 4.50),
(129, 3, 'Zeszyt A5 - 96kart.', 'ZZ1', 'Zeszyt A4 w kolorowych okładkach 96 kartkowy', 5.50),
(130, 3, 'Przekładki  A4', 'KB5', 'Przekładki  A4 w 12 kolorach, alfabetycznie ułożone', 8.40),
(131, 3, 'Przekładki poziome', 'KB6', 'Przekładki poziome w 12 różnych kolorach mix kartek w formacie 1/3 A4', 3.40),
(132, 4, 'Koperta ciemno zielona', 'KO1', 'Koperta w kolorze ciemno zielonym o wymiarach 110x220mm', 1.20),
(133, 4, 'Koperta różowa', 'KO2', 'Koperta w kolorze różowym o wymiarach 110x220mm', 1.20),
(134, 4, 'Koperta czerwona', 'KO3', 'Koperta w kolorze ciemnym czerwonym o wymiarach 114x162mm', 0.90),
(135, 4, 'Koperta jasno brązowa', 'KO4', 'Koperta w kolorze jasno brązowym o wymiarach 114x162mm', 0.90),
(136, 4, 'Koperta jasno zielona', 'KO5', 'Koperta w kolorze jasno zielonym o wymiarach 114x162mm', 0.90),
(137, 4, 'Koperta jasno niebieska', 'KO6', 'Koperta w kolorze jasno niebieskim o wymiarach 110x220mm', 1.20),
(138, 4, 'Koperta brązowa', 'KO7', 'Koperta w kolorze brązowym o wymiarach 114x162mm', 0.90),
(139, 4, 'Koperta czerwona', 'KO8', 'Koperta w kolorze czerwonym o wymiarach 110x220mm', 1.20),
(140, 4, 'Koperta pomarańczowa', 'KO9', 'Koperta w kolorze pomarańczowym o wymiarach 114x162mm', 0.90),
(141, 4, 'Koperta morska', 'KO10', 'Koperta w kolorze morskim o wymiarach 114x162mm', 0.90),
(142, 4, 'Koperta ciemno różowa', 'KO11', 'Koperta w kolorze ciemno różowym o wymiarach 110x220mm', 1.20);
